#!/bin/bash
# Setup Gradle proxy configuration for environments with authenticated HTTP proxies.
#
# This script:
# 1. Starts the auth proxy (if not already running)
# 2. Configures Gradle to use it via ~/.gradle/gradle.properties
#
# Usage:
#   source scripts/setup-gradle-proxy.sh
#
# After running, Gradle builds will work through the proxy.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROXY_SCRIPT="$SCRIPT_DIR/gradle-auth-proxy.py"
LOCAL_PROXY_PORT=3128

# Check if we need proxy (look for https_proxy env var with auth)
if [[ -z "$https_proxy" ]] && [[ -z "$HTTPS_PROXY" ]]; then
    echo "No https_proxy environment variable set - proxy setup not needed"
    return 0 2>/dev/null || exit 0
fi

PROXY_URL="${https_proxy:-$HTTPS_PROXY}"
if [[ "$PROXY_URL" != *"@"* ]]; then
    echo "Proxy URL doesn't contain credentials - using standard proxy"
    return 0 2>/dev/null || exit 0
fi

# Check for required tools - exit gracefully if missing
command -v nc >/dev/null 2>&1 || { echo "nc not found - skipping proxy setup"; return 0 2>/dev/null || exit 0; }
command -v python3 >/dev/null 2>&1 || { echo "python3 not found - skipping proxy setup"; return 0 2>/dev/null || exit 0; }

echo "Setting up Gradle proxy authentication..."

# Check if proxy is already running
if nc -z 127.0.0.1 $LOCAL_PROXY_PORT 2>/dev/null; then
    echo "Auth proxy already running on port $LOCAL_PROXY_PORT"
else
    echo "Starting auth proxy..."
    python3 "$PROXY_SCRIPT" &
    PROXY_PID=$!
    sleep 2

    if nc -z 127.0.0.1 $LOCAL_PROXY_PORT 2>/dev/null; then
        echo "Auth proxy started (PID: $PROXY_PID)"
    else
        echo "ERROR: Failed to start auth proxy"
        return 1 2>/dev/null || exit 1
    fi
fi

# Configure Gradle to use local proxy
mkdir -p ~/.gradle
cat > ~/.gradle/gradle.properties << 'EOF'
# HTTP Proxy Configuration - use local auth proxy
# This is auto-generated by setup-gradle-proxy.sh
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=3128
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=3128
systemProp.http.nonProxyHosts=localhost
EOF

echo "Gradle proxy configured in ~/.gradle/gradle.properties"
echo ""
echo "Gradle builds will now work through the authenticated proxy."
echo "Run './gradlew build' to test."
